### ISSUE TITLE
overbright lights 

### ISSUE THREAD

**Issue by ghost** [Varkalandar/imp_city#9]
Some lights are too bright sometimes, I do not know what could do that:

![3bugs-impcity](https://github.com/Varkalandar/imp_city/assets/1316300/9c24585c-de44-47f2-8251-a2b9f63b265a)

I hope I do not put pressure with those bug reports, and thanks again for the time you spend on this game.

**Comment by Varkalandar** [comment]
Don't worry about too many reports, they are very valuable to me. I had this effect in my tests too, it happens if the game places two (or more) lights in a place where there should be only one. I had fixed one cause of this, but it seems there are more.

I'll look into this, it should not happen. Same for the empty slot. There are clearly some problems in the new room furnishing code.

**Comment by Varkalandar** [comment]
Should be fixed in v0.26. Changing the room (by adding or removing a square) should set up furniture and lights properly and fix the problems present.

**Comment by ghost** [comment]
Still happens sadly, see #8 for the screenshots and a savegame.

**Comment by Varkalandar** [comment]
I see. I'll investigate the causes.

**Comment by Varkalandar** [comment]
I think it's finally all solved in the 0.27 (one can always hope ...)
